/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Client = IDL.Record({
  'clientId' : IDL.Nat,
  'gstNumber' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
});
export const SavedItem = IDL.Record({
  'rate' : IDL.Nat,
  'description' : IDL.Text,
  'itemCode' : IDL.Text,
  'itemName' : IDL.Text,
  'taxRate' : IDL.Nat,
  'taxType' : IDL.Variant({
    'igst' : IDL.Null,
    'none' : IDL.Null,
    'cgst_sgst' : IDL.Null,
  }),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const InvoiceStatus = IDL.Variant({
  'paid' : IDL.Null,
  'finalized' : IDL.Null,
  'overdue' : IDL.Null,
  'draft' : IDL.Null,
});
export const LineItem = IDL.Record({
  'rate' : IDL.Nat,
  'itemName' : IDL.Text,
  'discount' : IDL.Nat,
  'quantity' : IDL.Nat,
  'taxRate' : IDL.Nat,
  'taxType' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'paid' : IDL.Null,
  'unpaid' : IDL.Null,
  'partial' : IDL.Null,
});
export const Invoice = IDL.Record({
  'status' : InvoiceStatus,
  'lineItems' : IDL.Vec(LineItem),
  'client' : Client,
  'paymentStatus' : PaymentStatus,
  'dueDate' : IDL.Text,
  'totalTax' : IDL.Nat,
  'grandTotal' : IDL.Nat,
  'invoiceDate' : IDL.Text,
  'invoiceNumber' : IDL.Nat,
  'totalDiscount' : IDL.Nat,
  'subtotal' : IDL.Nat,
});
export const InvoiceWithExtras = IDL.Record({
  'status' : InvoiceStatus,
  'lineItems' : IDL.Vec(LineItem),
  'client' : Client,
  'paymentStatus' : PaymentStatus,
  'dueDate' : IDL.Text,
  'totalTax' : IDL.Nat,
  'grandTotal' : IDL.Nat,
  'invoiceDate' : IDL.Text,
  'invoiceNumber' : IDL.Nat,
  'totalDiscount' : IDL.Nat,
  'subtotal' : IDL.Nat,
  'bankDetails' : IDL.Opt(IDL.Text),
  'termsAndConditions' : IDL.Opt(IDL.Text),
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Plan = IDL.Variant({
  'pro_single' : IDL.Null,
  'pro_bundle' : IDL.Null,
  'free' : IDL.Null,
});
export const BusinessProfile = IDL.Record({
  'gstNumber' : IDL.Text,
  'logo' : ExternalBlob,
  'plan' : Plan,
  'businessName' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'remainingInvoiceCredits' : IDL.Nat,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'gstNumber' : IDL.Text,
  'logo' : ExternalBlob,
  'plan' : Plan,
  'businessName' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'remainingInvoiceCredits' : IDL.Nat,
  'phone' : IDL.Text,
});
export const PaymentData = IDL.Record({
  'paymentStatus' : IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  }),
  'plan' : Plan,
  'timestamp' : IDL.Int,
  'stripeSessionId' : IDL.Text,
  'invoiceCredits' : IDL.Nat,
  'paymentAmount' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addClient' : IDL.Func([Client], [], []),
  'addSavedItem' : IDL.Func([SavedItem], [], []),
  'adminGetStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'freePlanCount' : IDL.Nat,
          'totalInvoiceCredits' : IDL.Nat,
          'proBundleCount' : IDL.Nat,
          'proSingleCount' : IDL.Nat,
          'totalInvoices' : IDL.Nat,
          'userCount' : IDL.Nat,
        }),
      ],
      [],
    ),
  'adminGetUserInvoiceCount' : IDL.Func([IDL.Principal], [IDL.Nat], []),
  'adminUpgradeUserPlan' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'autoSaveDraft' : IDL.Func([InvoiceWithExtras], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createInvoice' : IDL.Func([InvoiceWithExtras], [IDL.Nat], []),
  'deleteClient' : IDL.Func([IDL.Nat], [], []),
  'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
  'deleteSavedItem' : IDL.Func([IDL.Text], [], []),
  'getBusinessProfile' : IDL.Func([], [IDL.Opt(BusinessProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(InvoiceWithExtras)], ['query']),
  'getStripePaymentHistory' : IDL.Func([], [IDL.Vec(PaymentData)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'listDraftInvoices' : IDL.Func([], [IDL.Vec(InvoiceWithExtras)], ['query']),
  'listInvoices' : IDL.Func([], [IDL.Vec(InvoiceWithExtras)], ['query']),
  'listSavedItems' : IDL.Func([], [IDL.Vec(SavedItem)], ['query']),
  'purchaseInvoiceCredits' : IDL.Func(
      [IDL.Text, IDL.Nat, Plan, IDL.Nat],
      [],
      [],
    ),
  'saveBusinessProfile' : IDL.Func([BusinessProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateClient' : IDL.Func([Client], [], []),
  'updateInvoice' : IDL.Func([InvoiceWithExtras], [], []),
  'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
  'updateSavedItem' : IDL.Func([SavedItem], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Client = IDL.Record({
    'clientId' : IDL.Nat,
    'gstNumber' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SavedItem = IDL.Record({
    'rate' : IDL.Nat,
    'description' : IDL.Text,
    'itemCode' : IDL.Text,
    'itemName' : IDL.Text,
    'taxRate' : IDL.Nat,
    'taxType' : IDL.Variant({
      'igst' : IDL.Null,
      'none' : IDL.Null,
      'cgst_sgst' : IDL.Null,
    }),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const InvoiceStatus = IDL.Variant({
    'paid' : IDL.Null,
    'finalized' : IDL.Null,
    'overdue' : IDL.Null,
    'draft' : IDL.Null,
  });
  const LineItem = IDL.Record({
    'rate' : IDL.Nat,
    'itemName' : IDL.Text,
    'discount' : IDL.Nat,
    'quantity' : IDL.Nat,
    'taxRate' : IDL.Nat,
    'taxType' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'paid' : IDL.Null,
    'unpaid' : IDL.Null,
    'partial' : IDL.Null,
  });
  const Invoice = IDL.Record({
    'status' : InvoiceStatus,
    'lineItems' : IDL.Vec(LineItem),
    'client' : Client,
    'paymentStatus' : PaymentStatus,
    'dueDate' : IDL.Text,
    'totalTax' : IDL.Nat,
    'grandTotal' : IDL.Nat,
    'invoiceDate' : IDL.Text,
    'invoiceNumber' : IDL.Nat,
    'totalDiscount' : IDL.Nat,
    'subtotal' : IDL.Nat,
  });
  const InvoiceWithExtras = IDL.Record({
    'status' : InvoiceStatus,
    'lineItems' : IDL.Vec(LineItem),
    'client' : Client,
    'paymentStatus' : PaymentStatus,
    'dueDate' : IDL.Text,
    'totalTax' : IDL.Nat,
    'grandTotal' : IDL.Nat,
    'invoiceDate' : IDL.Text,
    'invoiceNumber' : IDL.Nat,
    'totalDiscount' : IDL.Nat,
    'subtotal' : IDL.Nat,
    'bankDetails' : IDL.Opt(IDL.Text),
    'termsAndConditions' : IDL.Opt(IDL.Text),
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Plan = IDL.Variant({
    'pro_single' : IDL.Null,
    'pro_bundle' : IDL.Null,
    'free' : IDL.Null,
  });
  const BusinessProfile = IDL.Record({
    'gstNumber' : IDL.Text,
    'logo' : ExternalBlob,
    'plan' : Plan,
    'businessName' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'remainingInvoiceCredits' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'gstNumber' : IDL.Text,
    'logo' : ExternalBlob,
    'plan' : Plan,
    'businessName' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'remainingInvoiceCredits' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const PaymentData = IDL.Record({
    'paymentStatus' : IDL.Variant({
      'pending' : IDL.Null,
      'completed' : IDL.Null,
    }),
    'plan' : Plan,
    'timestamp' : IDL.Int,
    'stripeSessionId' : IDL.Text,
    'invoiceCredits' : IDL.Nat,
    'paymentAmount' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addClient' : IDL.Func([Client], [], []),
    'addSavedItem' : IDL.Func([SavedItem], [], []),
    'adminGetStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'freePlanCount' : IDL.Nat,
            'totalInvoiceCredits' : IDL.Nat,
            'proBundleCount' : IDL.Nat,
            'proSingleCount' : IDL.Nat,
            'totalInvoices' : IDL.Nat,
            'userCount' : IDL.Nat,
          }),
        ],
        [],
      ),
    'adminGetUserInvoiceCount' : IDL.Func([IDL.Principal], [IDL.Nat], []),
    'adminUpgradeUserPlan' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'autoSaveDraft' : IDL.Func([InvoiceWithExtras], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createInvoice' : IDL.Func([InvoiceWithExtras], [IDL.Nat], []),
    'deleteClient' : IDL.Func([IDL.Nat], [], []),
    'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
    'deleteSavedItem' : IDL.Func([IDL.Text], [], []),
    'getBusinessProfile' : IDL.Func([], [IDL.Opt(BusinessProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(InvoiceWithExtras)], ['query']),
    'getStripePaymentHistory' : IDL.Func([], [IDL.Vec(PaymentData)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'listDraftInvoices' : IDL.Func([], [IDL.Vec(InvoiceWithExtras)], ['query']),
    'listInvoices' : IDL.Func([], [IDL.Vec(InvoiceWithExtras)], ['query']),
    'listSavedItems' : IDL.Func([], [IDL.Vec(SavedItem)], ['query']),
    'purchaseInvoiceCredits' : IDL.Func(
        [IDL.Text, IDL.Nat, Plan, IDL.Nat],
        [],
        [],
      ),
    'saveBusinessProfile' : IDL.Func([BusinessProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateClient' : IDL.Func([Client], [], []),
    'updateInvoice' : IDL.Func([InvoiceWithExtras], [], []),
    'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
    'updateSavedItem' : IDL.Func([SavedItem], [], []),
    'requestPhoneOtp' : IDL.Func([IDL.Text], [IDL.Text], []),
    'verifyPhoneOtp' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'wrongOtp' : IDL.Null, 'expired' : IDL.Null, 'notFound' : IDL.Null })],
        [],
      ),
    'getLinkedPhone' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'isPhoneRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };