/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BusinessProfile {
  'gstNumber' : string,
  'logo' : ExternalBlob,
  'plan' : Plan,
  'businessName' : string,
  'email' : string,
  'address' : string,
  'remainingInvoiceCredits' : bigint,
  'phone' : string,
}
export interface Client {
  'clientId' : bigint,
  'gstNumber' : string,
  'name' : string,
  'email' : string,
  'address' : string,
  'companyName' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface Invoice {
  'status' : InvoiceStatus,
  'lineItems' : Array<LineItem>,
  'client' : Client,
  'paymentStatus' : PaymentStatus,
  'dueDate' : string,
  'totalTax' : bigint,
  'grandTotal' : bigint,
  'invoiceDate' : string,
  'invoiceNumber' : bigint,
  'totalDiscount' : bigint,
  'subtotal' : bigint,
}
export interface InvoiceWithExtras {
  'status' : InvoiceStatus,
  'lineItems' : Array<LineItem>,
  'client' : Client,
  'paymentStatus' : PaymentStatus,
  'dueDate' : string,
  'totalTax' : bigint,
  'grandTotal' : bigint,
  'invoiceDate' : string,
  'invoiceNumber' : bigint,
  'totalDiscount' : bigint,
  'subtotal' : bigint,
  'bankDetails' : [] | [string],
  'termsAndConditions' : [] | [string],
}
export type InvoiceStatus = { 'paid' : null } |
  { 'finalized' : null } |
  { 'overdue' : null } |
  { 'draft' : null };
export interface LineItem {
  'rate' : bigint,
  'itemName' : string,
  'discount' : bigint,
  'quantity' : bigint,
  'taxRate' : bigint,
  'taxType' : string,
}
export interface PaymentData {
  'paymentStatus' : { 'pending' : null } |
    { 'completed' : null },
  'plan' : Plan,
  'timestamp' : bigint,
  'stripeSessionId' : string,
  'invoiceCredits' : bigint,
  'paymentAmount' : bigint,
}
export type PaymentStatus = { 'paid' : null } |
  { 'unpaid' : null } |
  { 'partial' : null };
export type Plan = { 'pro_single' : null } |
  { 'pro_bundle' : null } |
  { 'free' : null };
export interface SavedItem {
  'rate' : bigint,
  'description' : string,
  'itemCode' : string,
  'itemName' : string,
  'taxRate' : bigint,
  'taxType' : { 'igst' : null } |
    { 'none' : null } |
    { 'cgst_sgst' : null },
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'gstNumber' : string,
  'logo' : ExternalBlob,
  'plan' : Plan,
  'businessName' : string,
  'email' : string,
  'address' : string,
  'remainingInvoiceCredits' : bigint,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addClient' : ActorMethod<[Client], undefined>,
  'addSavedItem' : ActorMethod<[SavedItem], undefined>,
  'adminGetStats' : ActorMethod<
    [],
    {
      'freePlanCount' : bigint,
      'totalInvoiceCredits' : bigint,
      'proBundleCount' : bigint,
      'proSingleCount' : bigint,
      'totalInvoices' : bigint,
      'userCount' : bigint,
    }
  >,
  'adminGetUserInvoiceCount' : ActorMethod<[Principal], bigint>,
  'adminUpgradeUserPlan' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'autoSaveDraft' : ActorMethod<[InvoiceWithExtras], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createInvoice' : ActorMethod<[InvoiceWithExtras], bigint>,
  'deleteClient' : ActorMethod<[bigint], undefined>,
  'deleteInvoice' : ActorMethod<[bigint], undefined>,
  'deleteSavedItem' : ActorMethod<[string], undefined>,
  'getBusinessProfile' : ActorMethod<[], [] | [BusinessProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInvoice' : ActorMethod<[bigint], [] | [InvoiceWithExtras]>,
  'getStripePaymentHistory' : ActorMethod<[], Array<PaymentData>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listClients' : ActorMethod<[], Array<Client>>,
  'listDraftInvoices' : ActorMethod<[], Array<InvoiceWithExtras>>,
  'listInvoices' : ActorMethod<[], Array<InvoiceWithExtras>>,
  'listSavedItems' : ActorMethod<[], Array<SavedItem>>,
  'purchaseInvoiceCredits' : ActorMethod<
    [string, bigint, Plan, bigint],
    undefined
  >,
  'saveBusinessProfile' : ActorMethod<[BusinessProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateClient' : ActorMethod<[Client], undefined>,
  'updateInvoice' : ActorMethod<[InvoiceWithExtras], undefined>,
  'updatePaymentStatus' : ActorMethod<[bigint, PaymentStatus], undefined>,
  'updateSavedItem' : ActorMethod<[SavedItem], undefined>,
  'requestPhoneOtp' : ActorMethod<[string], string>,
  'verifyPhoneOtp' : ActorMethod<[string, string], { 'ok' : null } | { 'wrongOtp' : null } | { 'expired' : null } | { 'notFound' : null }>,
  'getLinkedPhone' : ActorMethod<[], [] | [string]>,
  'isPhoneRegistered' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];